Add note about deterministic key generation
Yubico/arkg-rfc pull request #12
Opened 2024-04-04 13:53 UTC by emlun

(2024-04-03) Review comments from @AltmannPeter and @sander: There are desired use cases for deterministically generated seed keys, such as that outlined in the example here.

I don't think the defined procedures really need to change, since this is rather an implementation detail for the delegating party. I think we can just note that implementations are free to make that choice, without defining an interoperability API for this.

(A formal definition of `ARKG-Generate-Seed` is needed just to tie `BL-Generate-Keypair` and `KEM-Generate-Keypair` together, but its implementation details are not important for interoperability, unlike `ARKG-Derive-Public-Key` and `ARKG-Derive-Secret-Key`.)

2024-04-04 21:05 UTC, ve7jtb approved these changes
LGTM

2024-04-08 08:24 UTC, AltmannPeter requested changes

2024-04-08 08:24 UTC, AltmannPeter commented on draft-bradleylundberg-cfrg-arkg.md
> +likely sampling random key distributions,
likely sampling uniformly random key distributions,

2024-04-08 08:24 UTC, AltmannPeter commented on draft-bradleylundberg-cfrg-arkg.md
> +as deriving keys deterministically from some given input key material.
"as deterministic functions for a given input."

`ARKG-Generate-Seed()` does not derive a key.

2024-04-08 08:24 UTC, AltmannPeter commented on draft-bradleylundberg-cfrg-arkg.md
> +This can be thought of as defining a single-use ARKG instance where these functions return a constant result.
"This can be thought of as defining a single-use ARKG instance where these function outputs are static."

2024-04-09 15:13 UTC, merged